### ISSUE TITLE
При смене пароле через форму вход невозможен

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#23]
**1. Страница на которой произошла ошибка**
https://lk.academicol.ru/personal/login

**2. Описание ошибки**
При смене пароле через форму вход невозможе

**3. Что ожидалось получить вместо ошибки**
После смены пароля через форму, вход возможен

**4. Скриншоты**
--

**5. Копия дебаг-лога если есть**
--

**Comment by nazbav** [comment]
Не подтверждено
