### ISSUE TITLE
Полоска выше на 1 пиксель

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#34]
1. Страница на которой произошла ошибка
https://lk.academicol.ru/payment

2. Описание ошибки
Полоска на один пиксель выше

3. Что ожидалось получить вместо ошибки
Полоска на один пиксель ниже

4. Скриншоты
![image](https://user-images.githubusercontent.com/29039987/141344153-53e956ce-7291-4abe-bc8a-8d619a0ecc31.png)

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Ошибки дизайна отклоняются.
