### ISSUE TITLE
Двойной вход в аккаунт

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#35]
1. Страница на которой произошла ошибка
https://lk.academicol.ru/profile/security

2. Описание ошибки
Завершаем все сеансы. Заходим и происходит двойной вход с интервалом в несколько секунд

3. Что ожидалось получить вместо ошибки
Один сеанс

4. Скриншоты
![image](https://user-images.githubusercontent.com/29039987/141348581-75239894-bdda-4188-aaf7-34c0348d9161.png)

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Не является ошибкой личного кабинета.

**Comment by nazbav** [comment]
Отложено в долгий ящик.
