### ISSUE TITLE
Открытие двух вкладок

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#36]
1. Страница на которой произошла ошибка
https://lk.academicol.ru/docs/index

2. Описание ошибки
Выбираем документ. Давим ПКМ и "Открыть в новой вкладке". Открывается две вкладки, одна из которых не рабочая

3. Что ожидалось получить вместо ошибки
Открытие одной рабочей вкладки

4. Скриншоты
![image](https://user-images.githubusercontent.com/29039987/141349268-1fbdbde0-dfc6-4a73-89b6-061c3eb4b46d.png)

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Ошибки дизайна отклоняются.
