### ISSUE TITLE
[критично] Удалился список участников при редактировании мероприятия

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#43]
1. Страница на которой произошла ошибка
https://admin-lk.academicol.ru/event/update?id=

2. Описание ошибки
Удалился список участников при редактировании мероприятия

3. Что ожидалось получить вместо ошибки
Не удалился список участников при редактировании мероприятия

4. Скриншоты
Нахуй

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Ошибка была вызвана ошибкой при ручной регистрации участников на мероприятия. Все записи на старые мероприятия снимались если записаться на новое
