### ISSUE TITLE
Ограничение в списке ручной регистрации на кол-во строк, расширить

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#44]
1. Страница на которой произошла ошибка
--

2. Описание ошибки
Ограничение в списке ручной регистрации на кол-во строк, расширить

3. Что ожидалось получить вместо ошибки
Расширенный

4. Скриншоты
--

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Расширенно до 100 человек в списке
