### ISSUE TITLE
Баг в системе регистрации на мероприятие

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#50]
1. Страница на которой произошла ошибка

2. Описание ошибки
Баг в системе регистрации на мероприятие из за которого все летит

3. Что ожидалось получить вместо ошибки
Стабильная работа

4. Скриншоты
--

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Устранено обновлением от 17.11.2021
