### ISSUE TITLE
При создании мероприятия, появляется кнопка не в том месте

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#52]
1. Страница на которой произошла ошибка
https://admin-lk.academicol.ru/event/create

2. Шаги воспроизведения
    1.  Открываем окно создания мероприятия
    2.  В поле описания давим "Код"
    3.  Открываем textarea во весь экран кнопкой "Во весь экран"

3. Описание ошибки
Из ниоткуда появляется кнопка "Создать"

4. Что ожидалось получить вместо ошибки
Кнопка создать не должна появляться

5. Скриншоты
![image](https://user-images.githubusercontent.com/29039987/143686104-5b0b223b-6bb2-4aa8-abd4-7ce93520ff1b.png)

6. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Не является ошибкой при стандартном сценарии использования Лк
