### ISSUE TITLE
Невозможно добавить изображение или файл в описание мероприятия

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#53]
1. Страница, на которой произошла ошибка
https://admin-lk.academicol.ru/event/create

2. Описание ошибки
При попытке загрузки добавить изображение или файл в описание мероприятия, происходит ошибка

3. Что ожидалось получить вместо ошибки
Загрузка фотографии/файла

4. Скриншоты
![image](https://user-images.githubusercontent.com/29039987/143686354-5e0a8bb4-87f7-4f0d-ac12-6ac003e4cf7c.png)

5. Копия дебаг-лога если есть
--

**Comment by nazbav** [comment]
Исправлено в обновлении 28.11.2021
