### ISSUE TITLE
Не возможно отправить заявку на внесение корректировок в персональную информацию студента на сайте личного кабинета АНПОО "Академический колледж"

### ISSUE THREAD

**Issue by efsfssf** [Academicol/lk#9]
**1. Страница на которой произошла ошибка**
https://lk.academicol.ru/personal/actualization

**2. Описание ошибки**
Swift_TransportException
Connection could not be established with host smtp-pulse.com :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

**3. Что ожидалось получить вместо ошибки**
Отправка заявки

**4. Скриншоты**
![Снимок экрана 2021-09-21 213612](https://user-images.githubusercontent.com/29039987/134228412-935f4bc9-bbc8-4835-b3c0-cb58ee9421e3.png)

**5. Копия дебаг-лога если есть**
Нет

**Comment by nazbav** [comment]
Требует тщательной проверки
